[book]
authors = ["Lee Ting Ting", "Jacek Sieka", "Sacha Saint-Leger"]
language = "en"
multilingual = false
src = "src"
title = "The Nimbus Beacon Chain Book"

[output.html]
additional-css = ["custom.css"]
