# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: The Nimbus Guide
theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - content.tabs.link
  palette:
    scheme: default
    primary: orange
    accent: amber

# Support urls previously used by mdbook
use_directory_urls: false
repo_url: https://github.com/status-im/nimbus-eth2
edit_uri: edit/unstable/docs/the_nimbus_book/src
site_url: https://nimbus.guide
docs_dir: src

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      toc_depth: 3

nav:
  - About:
    - 'index.md'
    - 'philosophy.md'

  - Getting started:
    - 'quick-start.md'
    - 'run-a-validator.md'
    - 'migration.md'
    - 'metrics-pretty-pictures.md'
    - 'pi-guide.md'
    - 'el-light-client.md'

  - How-to:
    - Beacon node:
      - 'install.md'
      - 'build.md'
      - 'start-syncing.md'
      - 'trusted-node-sync.md'
      - 'web3-backup.md'

    - Validator:
      - 'deposit.md'
      - 'keys.md'
      - 'connect-eth2.md'
      - 'graffiti.md'
      - 'suggested-fee-recipient.md'
      - 'external-block-builder.md'
      - 'keep-an-eye.md'
      - 'voluntary-exit.md'
      - 'more-keys.md'
      - 'additional-validator.md'
      - 'validator-client.md'

    - General:
      - 'keep-updated.md'
      - 'eth1.md'
      - 'goerli-eth.md'
      - 'beacon-node-systemd.md'
      - 'log-rotate.md'
      - 'database-backup.md'
      - 'email-notifications.md'
      - 'profits.md'
      - 'health.md'
      - 'prater.md'

  - Security:
    - 'preparation.md'
    - 'security_issues.md'
    - 'audit.md'
    - 'distribution_internals.md'

  - Reference:
    - 'hardware.md'
    - Advanced options:
      - 'options.md'
      - 'networking.md'
      - 'optimistic-sync.md'
      - 'light-client-data.md'
      - 'logging.md'
      - 'validator-client-options.md'
      - 'validator-monitor.md'
      - 'doppelganger-detection.md'
    - "REST APIs":
      - 'rest-api.md'
      - 'keymanager-api.md'
    - Storage:
      - 'data-dir.md'
      - 'era-store.md'
      - 'history.md'
    - 'migration-options.md'
    - 'attestation-performance.md'
    - 'troubleshooting.md'
    - 'faq.md'
    - 'developers.md'
    - 'resources.md'
    - 'contribute.md'

  - Downloads:
    - 'binaries.md'
    - 'docker.md'
    - 'checksums.md'
