version: '{build}'

image: Visual Studio 2015

environment:
  # disable LFS file downloading during regular cloning
  GIT_LFS_SKIP_SMUDGE: 1

cache:
  - NimBinaries
  - p2pdCache
  - jsonTestsCache

matrix:
  # We always want 32 and 64-bit compilation
  fast_finish: false

platform:
  - x86
  - x64

install:
  - git submodule update --init --recursive
  # use the newest versions documented here: https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin
  - IF "%PLATFORM%" == "x86" SET PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH%
  - IF "%PLATFORM%" == "x64" SET PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%

  # LFS test fixtures
  - bash scripts\process_lfs.sh jsonTestsCache

build_script:
  # the 32-bit build is done on a 64-bit image, so we need to override the architecture
  - mingw32-make -j2 ARCH_OVERRIDE=%PLATFORM% CI_CACHE=NimBinaries update
  - mingw32-make -j2 ARCH_OVERRIDE=%PLATFORM% fetch-dlls

test_script:
  # the "go-checks" target fails in AppVeyor, for some reason; easier to disable than to debug
  - mingw32-make -j2 ARCH_OVERRIDE=%PLATFORM% DISABLE_GO_CHECKS=1 P2PD_CACHE=p2pdCache
  - mingw32-make -j2 ARCH_OVERRIDE=%PLATFORM% DISABLE_LFS_SCRIPT=1 DISABLE_GO_CHECKS=1 test

deploy: off

