language: c

# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - NimBinaries
    - rocksdbCache
    - jsonTestsCache

git:
  # when multiple CI builds are queued, the tested commit needs to be in the last X commits cloned with "--depth X"
  depth: 10
  # disable LFS file downloading during regular cloning
  lfs_skip_smudge: true

matrix:
  include:
    - os: linux
      sudo: required
      before_install:
        - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
    - os: osx
      before_install:
        - launchctl setenv LIBRARY_PATH /usr/local/lib # for RocksDB

install:
  # build nim from our own branch - this to avoid the day-to-day churn and
  # regressions of the fast-paced Nim development while maintaining the
  # flexibility to apply patches
  - curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus/devel/build_nim.sh
  - env MAKE="make -j2" bash build_nim.sh Nim csources dist/nimble NimBinaries
  - export PATH=$PWD/Nim/bin:$PATH

  # build our own rocksdb to test with a fixed version that we think works
  - curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus/devel/build_rocksdb.sh
  - bash build_rocksdb.sh rocksdbCache

  # LFS test fixtures
  - scripts/process_lfs.sh jsonTestsCache

script:
  - nimble install -y --depsOnly
  - nimble test

