on:
  push:
    tags:
    - 'v*' # "v1.2.3"

name: Upload Release Asset

jobs:
  build-amd64:
    name: Linux AMD64 release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        id: make_dist
        run: |
          make dist-amd64
          cd dist
          ARCHIVE=nimbus-eth2_Linux_amd64_*.tar.gz
          echo "::set-output name=archive::"${ARCHIVE}
          echo "::set-output name=archive_dir::"${ARCHIVE%.tar.gz}
          tar -xzf ${ARCHIVE} ${ARCHIVE%.tar.gz}/build/nimbus_beacon_node.sha512sum
      - name: Upload archive artefact
        uses: actions/upload-artifact@v2
        with:
          name: Linux_amd64_archive
          path: ./dist/${{ steps.make_dist.outputs.archive }}
          retention-days: 2
      - name: Upload checksum artefact
        uses: actions/upload-artifact@v2
        with:
          name: Linux_amd64_checksum
          path: ./dist/${{ steps.make_dist.outputs.archive_dir }}/build/nimbus_beacon_node.sha512sum
          retention-days: 2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push a Docker image for end users
        run: |
          cd dist
          tar -xzf ${{ steps.make_dist.outputs.linux_amd64_archive }}
          mv nimbus-eth2_Linux_amd64_*/ ../docker/dist/binaries/nimbus-eth2
          cd ../docker/dist/binaries
          REFNAME="${{ github.ref }}"
          TAG="${REFNAME#refs/tags/}"
          DOCKER_BUILDKIT=1 docker build -f Dockerfile.amd64 -t statusim/nimbus-eth2:amd64-${TAG} -t statusim/nimbus-eth2:amd64-latest .
          docker push statusim/nimbus-eth2:amd64-${TAG}
          # FIXME: enable image pushing after testing
          #docker push statusim/nimbus-eth2:amd64-latest
  build-arm64:
    name: Linux ARM64 release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        id: make_dist
        run: |
          make dist-arm64
          cd dist
          ARCHIVE=nimbus-eth2_Linux_arm64v8_*.tar.gz
          echo "::set-output name=archive::"${ARCHIVE}
          echo "::set-output name=archive_dir::"${ARCHIVE%.tar.gz}
          tar -xzf ${ARCHIVE} ${ARCHIVE%.tar.gz}/build/nimbus_beacon_node.sha512sum
      - name: Upload archive artefact
        uses: actions/upload-artifact@v2
        with:
          name: Linux_arm64_archive
          path: ./dist/${{ steps.make_dist.outputs.archive }}
          retention-days: 2
      - name: Upload checksum artefact
        uses: actions/upload-artifact@v2
        with:
          name: Linux_arm64_checksum
          path: ./dist/${{ steps.make_dist.outputs.archive_dir }}/build/nimbus_beacon_node.sha512sum
          retention-days: 2
  build-arm:
    name: Linux ARM release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        id: make_dist
        run: |
          make dist-arm
          cd dist
          ARCHIVE=nimbus-eth2_Linux_arm32v7_*.tar.gz
          echo "::set-output name=archive::"${ARCHIVE}
          echo "::set-output name=archive_dir::"${ARCHIVE%.tar.gz}
          tar -xzf ${ARCHIVE} ${ARCHIVE%.tar.gz}/build/nimbus_beacon_node.sha512sum
      - name: Upload archive artefact
        uses: actions/upload-artifact@v2
        with:
          name: Linux_arm_archive
          path: ./dist/${{ steps.make_dist.outputs.archive }}
          retention-days: 2
      - name: Upload checksum artefact
        uses: actions/upload-artifact@v2
        with:
          name: Linux_arm_checksum
          path: ./dist/${{ steps.make_dist.outputs.archive_dir }}/build/nimbus_beacon_node.sha512sum
          retention-days: 2
  build-win64:
    name: Windows AMD64 release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        id: make_dist
        run: |
          make dist-win64
          cd dist
          ARCHIVE=nimbus-eth2_Windows_amd64_*.tar.gz
          echo "::set-output name=archive::"${ARCHIVE}
          echo "::set-output name=archive_dir::"${ARCHIVE%.tar.gz}
          tar -xzf ${ARCHIVE} ${ARCHIVE%.tar.gz}/build/nimbus_beacon_node.sha512sum
      - name: Upload archive artefact
        uses: actions/upload-artifact@v2
        with:
          name: Windows_amd64_archive
          path: ./dist/${{ steps.make_dist.outputs.archive }}
          retention-days: 2
      - name: Upload checksum artefact
        uses: actions/upload-artifact@v2
        with:
          name: Windows_amd64_checksum
          path: ./dist/${{ steps.make_dist.outputs.archive_dir }}/build/nimbus_beacon_node.sha512sum
          retention-days: 2
  prepare-release:
    name: Prepare release draft
    needs: [build-amd64, build-arm64, build-arm, build-win64]
    runs-on: ubuntu-latest
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v2
      - name: Create release notes
        run: |
          cat > release_notes.md <<EOF
          ## Notes

          ## SHA512 checksums

          ```text
          EOF
          echo '# Linux AMD64' >> release_notes.md
          cat Linux_amd64_checksum/* >> release_notes.md
          echo '# Linux ARM64' >> release_notes.md
          cat Linux_arm64_checksum/* >> release_notes.md
          echo '# Linux ARM' >> release_notes.md
          cat Linux_arm_checksum/* >> release_notes.md
          echo '# Windows AMD64' >> release_notes.md
          cat Windows_amd64_checksum/* >> release_notes.md
          echo '```' >> release_notes.md
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          body_path: release_notes.md
          files: |
            Linux_amd64_archive/*
            Linux_arm64_archive/*
            Linux_arm_archive/*
            Windows_amd64_archive/*

